let quote = [
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { quote: "Great things never come from comfort zones.", author: "Unknown" },
  { quote: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
  { quote: "Sometimes later becomes never. Do it now.", author: "Unknown" },
  { quote: "Little things make big days.", author: "Unknown" },
  { quote: "Don't stop when you're tired. Stop when you're done.", author: "Marilyn Monroe" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { quote: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { quote: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { quote: "Don't wait for opportunity. Create it.", author: "George Bernard Shaw" },
  { quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "Failure is not the opposite of success; it's part of success.", author: "Arianna Huffington" },
  { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { quote: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "You are stronger than you think.", author: "Unknown" },
  { quote: "Your limitation—it's only your imagination.", author: "Unknown" },
  { quote: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
  { quote: "Success is not for the lazy.", author: "Unknown" },
  { quote: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
  { quote: "Stay positive, work hard, make it happen.", author: "Unknown" },
  { quote: "Your only competition is who you were yesterday.", author: "Unknown" },
  { quote: "Make each day your masterpiece.", author: "John Wooden" },
  { quote: "You are capable of amazing things.", author: "Unknown" },
  { quote: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Life isn't about finding yourself. It's about creating yourself.", author: "George Bernard Shaw" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
  { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "You learn more from failure than from success.", author: "Unknown" },
  { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "You can't cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
  { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
  { quote: "The best way out is always through.", author: "Robert Frost" },
  { quote: "You don't find the happy life. You make it.", author: "Camilla Eyring Kimball" },
  { quote: "Be so good they can't ignore you.", author: "Steve Martin" },
  { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
  { quote: "A goal is a dream with a deadline.", author: "Napoleon Hill" },
  { quote: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
  { quote: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort" }]

let text = document.getElementById("quote")
let auth = document.getElementById("author")

function genquote(){
  let randIndx = Math.floor(Math.random()*quote.length)
 let finalquote = quote[randIndx].quote
 let finalauthor = quote[randIndx].author
text.innerHTML = finalquote;
auth.innerHTML = "~"+ finalauthor;
} 
